services:
  postgres:
    image: postgres:15
    container_name: gyulistv2-dev-postgres
    environment:
      POSTGRES_DB: gyulistv2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - gyulistv2-dev-network

  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    container_name: gyulistv2-dev
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/gyulistv2"
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
      API_URL: "http://localhost:3001"
      NODE_ENV: development
    volumes:
      - ..:/workspace:cached
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gyulistv2-dev-network
    command: sleep infinity

volumes:
  postgres_dev_data:

networks:
  gyulistv2-dev-network:
    driver: bridge




